### PR TITLE
add experimental hybrid based on arsd master

### PR DESCRIPTION
**Pull request by adamdruppe**
I slapped together this hybrid after thinking about it a bit in the blog Friday. It isn't fully tested but does OK so far so I thought it might be fun to add here and see how it stacks up.

I also fixed an old buffering bug in my write function that harmed performance across the board (it did buffering with the concat operator, already an inefficient way to do it.... but then ignored the buffer and wrote the pieces in a loop anyway, leading to like 8 syscalls when only one was necessary! This killed performance in the hello world case, fixing that helped the existing things a lot too.)

I'll be quite amused if it moves up to the middle of the pack with less than one day's work and no api change :)

### CODE REVIEW

**Comment by adamdruppe** [comment]
BTW the hybrid just is the thread server with `-version=cgi_use_fiber` and `-version=cgi_use_fork` combined.

So it starts as a thread server then forks off a copy of itself. The reason for this is while one copy is stopped doing a GC collection, the other can keep going so the back queue doesn't get as long (it really only helps the rare top 0.1% of cases but still).

Then the thread server, with -version=cgi_use_thread, instead of sending connections off to worker threads to process directly, instead sends connections off to worker fibers. The worker threads then pick up and resume worker fibers as they become ready. (this means the fibers can jump around threads!)

Not actually a whole lot of code to implement this but there's a lot of risk of breakage so I'm not quite ready to formally release yet, hence the dependency on ~master instead of a numbered version.

**Comment by tchaloupka** [comment]
Hi Adam, thanks for this.
I'll try to rerun the tests over the night (as it takes pretty long already) with other changes too and will post the results tomorrow (hopefully).

Only thing I'd like to make sure of is the test category of this. As currently I've only published singleCore tests and marked arsd singleCore too even though it's really not (as it's using fork or multiple threads). But as it hasn't used epoll/io_uring it seems fair enough to me to mark it as that and compare this traditional approach with the modern async event loops.
But with this change on the first look I'm not so sure if it still holds that, and I'm more inclined to `multiCore` category here.

I should probably modify other tests to return same total response size as `arsd` as currently it returns the largest response and will be affected by it in a negative way.

**Comment by adamdruppe** [comment]
On Mon, Sep 28, 2020 at 10:20:01AM -0700, Tomáš Chaloupka wrote:
> Only thing I'd like to make sure of is the test category of this. As currently I've only published singleCore tests and marked arsd singleCore too even though it's really not (as it's using fork or multiple threads).

Yeah, I was kinda curious about that too. I searched your code and
didn't even really understand what the difference was.

If anything, I'd probably call epoll single core (though it can
obviously be spread across worker threads too)...

> I should probably modify other tests to return same total response size as `arsd` as currently it returns the largest response and will be affected by it in a negative way.

This might have changed since part of the buffer bug was it sending a
bit more than it needed to.

But the other changes might be my default header set - I also put out no
cache headers and such. See:

$ curl -v http://localhost:4000
*   Trying 127.0.0.1:4000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4000 (#0)
> GET / HTTP/1.1
> Host: localhost:4000
> User-Agent: curl/7.66.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Mon, 28 Sep 2020 17:40:58 GMT
< Cache-Control: private, no-cache="set-cookie"
< Expires: 0
< Pragma: no-cache
< Content-Type: text/html; charset=utf-8
< Content-Length: 13
<
* Connection #0 to host localhost left intact
Hello, world!



That combination is probably obsolete - it made a difference back with
IE6, this is an old library! - but still it was a sane default for a
long time and doesn't hurt much really. Especially with the buffer bug
fixed so it all goes into one tcp packet again now.

**Comment by tchaloupka** [comment]
Ok, so I've got all tests to output 192B for the whole response (including header).

About single/multiCore.
My idea was to primarily test performance when run on the single core and single thread (as all but arsd used epoll/io_uring loops in a single thread). This is also easier to test on the localhost as load generator won't interfere too much with the test.

* C epoll, uring, nginx - all are using just one worker process with single thread event loop (nginx has a variant for multiCore too)
* D - uring, epoll, eventcore, hunt, lighttp, vibe-core, vibe-d - all uses only single thread event loop
  * Hunt - well with this I'm not so sure, using `ioThreadSize` to set 1 worker, but hunt-http is too slow and hunt-pico pretty fast - seems odd
* D - photon - I should investigate this and probably patch it as it seems to work with multiple threads based on [this](https://github.com/DmitryOlshansky/photon/blob/master/src/photon/linux/core.d#L401)
* .Net Core - should work with one thread (`options.IOQueueCount = threadCount`)
* Go - using `GOMAXPROCS` to set workers number
* Rust - using `workers` setter to set to single worker

I would like to add generic prefork runner that'll just fork multiple processes (and pin them to the available cores) for normally just single thread tests with shared port and let the others use their own multi core scheduler.

I haven't seen this scenario tested in other http benchmarks, but it seems to me that this is too an interesting scenario to see how it behaves ie without shedulers to pass work between threads - especially with just one thread epoll/io_uring event loops.

**Comment by adamdruppe** [comment]
On Mon, Sep 28, 2020 at 12:10:11PM -0700, Tomáš Chaloupka wrote:
> About single/multiCore.
> My idea was to primarily test performance when run on the single core and single thread (as all but arsd used epoll/io_uring loops in a single thread). This is also easier to test on the localhost as load generator won't interfere too much with the test.

Yeah, I have ways to do it for debugging purposes too:

-version=cgi_no_threads

with the thread thing and a static ctor/custom main that changes `processPoolSize`
for processes. (I think I'll document that for the formal release and
put it in the new config struct so it is easier to set. Then do
something similar for number of worker threads as well.)

But the only documentation these have is `// NEVER USE THIS` because it
is kinda terrible for any actual use.

Ruby on Rails' godawful default WebBRICK is single threaded like this
too and it is actually really easy to lock it up, even when just testing
code locally. (That awful thing will outright deadlock if you have a
thing that issues a request to itself which I learned the hard way last
year trying to test some trivial code. Pretty sure at least the vibe
style event loop can handle that case, but it is still prone to problems
if you call any blocking function, whether third party i/o or just slow
cpu crunching code. This is why I was so hesitant to go event at all for
the core server, it must be done very carefully to actually work as well
as it claims and most user code simply isn't that careful. And even when
it is, you miss out on most libraries that aren't that careful.)

> I would like to add generic prefork runner that'll just fork multiple processes (and pin them to the available cores) for normally just single thread tests with shared port and let the others use their own multi core scheduler.

You might hit "address already in use" problems depending on how they
bind. It is best to fork after listening so they can share that.

And on Windows, of course, you don't have fork() at all... you must
thread and/or fiber there. (It's built in thread and fiber facilities
are excellent though.)

If the framework doesn't offer some built-in facility to handle this
itself, I'd put that as a very serious negative, unless, of course, it
uses CGI (or its simple/fast variants), which explicitly are designed to
allow pushing it off to another layer :)


> I haven't seen this scenario tested in other http benchmarks, but it seems to me that this is too an interesting scenario to see how it behaves ie without shedulers to pass work between threads - especially with just one thread epoll/io_uring event loops.

Aye. Kinda interesting to test simulated slow connections with larger
responses and slow code too, just to see how it is handled. (gzipping
larger responses is very useful!) One slow user or endpoint shouldn't
break others. Even a slow worker thread in an async/await type situation
shouldn't affect the latency of other users - thread prioritization
might be needed.

At some point you might just say "well fix your code" but there is value
in a framework being friendlier too.

**Comment by tchaloupka** [comment]
It would be great If we can make a new hybrid configuration in both variants.

I've run just a fast check with 8 clients on my main rig (8core 16 threads AMD processor) and:

| Language | Framework | Category |    Name    |   Req    |  RPS   |   BPS    |  max  |  50%  |  75%  |  90%  |  99%  |
|:--------:|:---------:|:--------:|:----------:| --------:| ------:| --------:| -----:| -----:| -----:| -----:| -----:|
|  dlang   |  photon   |  micro   |            | 42322122 | 352684 | 67715395 | 22.82 | 0.019 | 0.023 |  0.03 |  1.21 |
|  dlang   |   arsd    | platform | processes  | 41127973 | 342733 | 65804756 |  9.35 | 0.021 | 0.026 | 0.028 | 0.053 |
|    c     |   epoll   |  micro   | raw - lvl  | 23457862 | 195482 | 37532579 |   3.4 | 0.035 |  0.04 | 0.065 | 0.077 |
|    c     | io_uring  |  micro   |    raw     | 22295220 | 185793 | 35672352 |  2.86 | 0.042 | 0.045 | 0.046 | 0.051 |
|    c     |   epoll   |  micro   | raw - edge | 22277576 | 185646 | 35644121 |  2.75 | 0.042 | 0.044 | 0.046 | 0.051 |
|    c     |   nginx   | platform |            | 17275853 | 143965 | 27641364 |  8.67 | 0.055 | 0.057 |  0.06 | 0.066 |
|  dlang   |   arsd    | platform |   hybrid   |  8235759 |  68631 | 13177214 | 13.31 | 0.028 |  0.89 |   1.9 |  4.35 |
|  dlang   |   arsd    | platform |  threads   |  7986066 |  66550 | 12777705 |    13 | 0.027 | 0.837 |  1.66 |  3.91 |

Run with: `_suite/runner.d bench --tool wrk -c 8 -d 120 --type singleCore arsd c/ photon`

It's another evidence that photon isn't just a single core one.
And arsd/processes is on top probably just because it scales between cores and so all the HTTP parsing, routing, etc is done in other core for each client but for raw tests it's all handled in the single core (well basically raw tests don't handle anything related to HTTP, they are just checking that the received data ends with \r\n\r\n and send data from prepared buffer - that's why it's suspicious if some other test beats these).
But still pretty high above hybrid/threads variants.

**Comment by adamdruppe** [comment]
Yeah, that buffering bug was killing my processes performance before. Fixing that made a huge difference, turned 8 syscalls into 1. (Though it still has the downside of a slow / idle connection of being able to monopolize a worker. I'd kinda love if I can dynamically detect that and spawn new workers... but idk).

The beauty of prefork processes is the Linux kernel does basically all the work and it does it in very few context switches. When you call blocking accept/send/recv, you're added to the *kernel's* event loop and then you're notified when the operation is done. One system call, one context switch. Furthermore the userland is simplified since there's no dynamic allocations, no fiber state management, etc.

With my hybrid approach, there's *four* system calls to do the same thing: receive, see it would block and epoll_ctrl, epoll_wait until it is free, then receive again to retry. Accept is similar but include the fiber setup.

Even with the pure single core model like vibe (I'm pretty sure anyway) uses, there's still at least two: epoll_wait, then some userland processing before you receive again. System calls are expensive when you aren't doing much else.

And the kernel itself is a common baseline for all of them so it is hard to beat just letting it do 90% of the work!

Add in the crash protection of processes and library compatibility and they're legitimately hard to beat (on Linux anyway).... until you have a huge number of mostly-idle connections. That's where the userspace event systems shine.

**Pull request merged**
